/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-09-24 14:48:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Cliente;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import DAO.UserDAO;
import DTO.UserDTO;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DTO.UserDTO");
    _jspx_imports_classes.add("DAO.UserDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"pt-br\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\">\r\n");
      out.write("    <title>Lohane Lima</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("  \r\n");
      out.write("   input[readonly] {\r\n");
      out.write("         background-color: #f2f2f2; /* Define a cor de fundo para campos desabilitados */\r\n");
      out.write("    color: #888888;\r\n");
      out.write("    }\r\n");
      out.write("    .modal {\r\n");
      out.write("    display: none; \r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    overflow: auto;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.4);\r\n");
      out.write("    }\r\n");
      out.write("    .modal-content {\r\n");
      out.write("    background-color: #ffccb4;\r\n");
      out.write("    position: absolute; /* Mude para absolute */\r\n");
      out.write("    left: 50%; /* Centralize horizontalmente na tela */\r\n");
      out.write("    top: 50%; /* Centralize verticalmente na tela */\r\n");
      out.write("    transform: translate(-50%, -50%); /* Centralize tanto horizontal quanto verticalmente */\r\n");
      out.write("    margin: 0 auto; /* Remova a margem anterior */\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border: 2px solid #888;\r\n");
      out.write("    width: 80%;\r\n");
      out.write("    max-width: 400px;\r\n");
      out.write("}\r\n");
      out.write("    .close {\r\n");
      out.write("    color: #3f3f3f;\r\n");
      out.write("    float: right;\r\n");
      out.write("    font-size: 28px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .close:hover,\r\n");
      out.write("    .close:focus {\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .modal-title {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    form {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    }\r\n");
      out.write("    input,\r\n");
      out.write("    button {\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    }\r\n");
      out.write("    .caixa-form {\r\n");
      out.write("    padding: 9px;\r\n");
      out.write("    border-radius: 9px;\r\n");
      out.write("    }\r\n");
      out.write("    button {\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    background-color: rgb(233, 188, 129);\r\n");
      out.write("    color: black;\r\n");
      out.write("    border: none;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-weight: 600;\r\n");
      out.write("    }\r\n");
      out.write("    button:hover {\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: rgb(186, 155, 113);\r\n");
      out.write("    }\r\n");
      out.write("    .titulo h1 {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    text-decoration: underline;\r\n");
      out.write("    }\r\n");
      out.write("    .titulo h2 {\r\n");
      out.write("    font-size: 12px;\r\n");
      out.write("    margin-top: 6px;\r\n");
      out.write("    margin-bottom: 6px;\r\n");
      out.write("    }\r\n");
      out.write("    form {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    flex-direction: column;\r\n");
      out.write("    }\r\n");
      out.write("    input,select {\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    padding: 10px;\r\n");
      out.write("    border-radius: 3px;\r\n");
      out.write("    outline: none;\r\n");
      out.write("    }\r\n");
      out.write("    input:hover {\r\n");
      out.write("    border-bottom: 3px solid rgb(186, 155, 113);\r\n");
      out.write("    }\r\n");
      out.write("    .usuario{\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  <body>\r\n");
      out.write("      ");
 
      String nome = request.getParameter("nome_User");
      String email = request.getParameter("email_User");
      String senha = request.getParameter("senha_User");
      int id = Integer.parseInt(request.getParameter("id_User"));
        
        
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("      // open modal de logar\r\n");
      out.write("      function Alterar_User() {\r\n");
      out.write("        document.getElementById(\"alterar\").style.display = \"block\";\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      // open modal de register \r\n");
      out.write("      function Excluir_User() {\r\n");
      out.write("        document.getElementById(\"excluir\").style.display = \"block\";\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      // close modal\r\n");
      out.write("      function closeModal() {\r\n");
      out.write("        document.getElementById(\"alterar\").style.display = \"none\";\r\n");
      out.write("        document.getElementById(\"excluir\").style.display = \"none\";\r\n");
      out.write("        document.getElementById(\"form-carrinho\").style.display = \"none\";\r\n");
      out.write("      }\r\n");
      out.write("      \r\n");
      out.write("      // Emissão de alerta ao retornar da página de cadastro.\r\n");
      out.write("      var retorna = new URLSearchParams(window.location.search);\r\n");
      out.write("      var elemento = retorna.get('conf');\r\n");
      out.write("      \r\n");
      out.write("      switch (elemento) {\r\n");
      out.write("        case 'altera':\r\n");
      out.write("          setTimeout(function() {\r\n");
      out.write("            alert('Usuário alterado!');\r\n");
      out.write("          }, 100);\r\n");
      out.write("          break;\r\n");
      out.write("          \r\n");
      out.write("        case 'existe':\r\n");
      out.write("            setTimeout(function() {\r\n");
      out.write("              alert('Este usuário não pode ser alterado!');\r\n");
      out.write("            }, 100);\r\n");
      out.write("            break;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("   \r\n");
      out.write("      \r\n");
      out.write("      function Form_carrinho(nomeProduto, quantidade, preco, imagemUrl, idUsuario, tamanhoSelecionado) {\r\n");
      out.write("    	  var selectTamanho = document.getElementById(\"tamanho\");\r\n");
      out.write("\r\n");
      out.write("    	  // Adicionar um evento onchange ao selectTamanho\r\n");
      out.write("    	  selectTamanho.onchange = function () {\r\n");
      out.write("    	    // Obter a opção selecionada\r\n");
      out.write("    	    var opcaoSelecionada = selectTamanho.options[selectTamanho.selectedIndex];\r\n");
      out.write("\r\n");
      out.write("    	    // Obter o preço da opção selecionada usando o atributo data-preco\r\n");
      out.write("    	    var precoSelecionado = parseFloat(opcaoSelecionada.getAttribute(\"data-preco\"));\r\n");
      out.write("    	    var tamanho = opcaoSelecionada.getAttribute(\"value\");\r\n");
      out.write("\r\n");
      out.write("    	    // Certificar-se de que preco e precoSelecionado são números\r\n");
      out.write("    	    preco = parseFloat(preco);\r\n");
      out.write("\r\n");
      out.write("    	    // Calcular o novo preço somando ao preço atual\r\n");
      out.write("    	    var novo_valor = preco + precoSelecionado;\r\n");
      out.write("\r\n");
      out.write("    	    // Atualizar o campo de preço\r\n");
      out.write("    	    document.getElementById(\"preco\").value = novo_valor.toFixed(2); // Formate o preço como desejar\r\n");
      out.write("\r\n");
      out.write("    	    // Atualizar o campo de tamanho\r\n");
      out.write("    	    document.getElementById(\"tam\").value = tamanho;\r\n");
      out.write("    	  };\r\n");
      out.write("    	  preco = parseFloat(preco);\r\n");
      out.write("    	  document.getElementById(\"nome_produto\").value = nomeProduto;\r\n");
      out.write("    	  document.getElementById(\"quantidade\").value = quantidade;\r\n");
      out.write("    	  document.getElementById(\"tam\").value = tamanhoSelecionado; // Defina o tamanho selecionado aqui\r\n");
      out.write("    	  document.getElementById(\"preco_padrao\").value = preco; // Defina o tamanho selecionado aqui\r\n");
      out.write("\r\n");
      out.write("    	  document.getElementById(\"imagem_url\").value = imagemUrl;\r\n");
      out.write("    	  document.getElementById(\"id_usuario\").value = idUsuario;\r\n");
      out.write("\r\n");
      out.write("    	  // Abra o modal ou realize outras ações com os valores\r\n");
      out.write("    	  document.getElementById(\"form-carrinho\").style.display = \"block\";\r\n");
      out.write("    	}\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("    </script>\r\n");
      out.write("    <div class=\"background\">\r\n");
      out.write("    <header>\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1>Styloh</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"cabeçalho-link\">\r\n");
      out.write("        <a href=\"#\">Inicio</a>\r\n");
      out.write("        <a href=\"#\">Destaque</a>\r\n");
      out.write("        <a href=\"#\">Novo</a>\r\n");
      out.write("        <a href=\"#contato\">Contato</a>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("          <a href=\"#\">Login</a>\r\n");
      out.write("          <div class=\"dropdown-content\">\r\n");
      out.write("            <a href=\"../PG_Principal/index.html\">Sair</a>\r\n");
      out.write("            <a href=\"#\" onclick=\"Alterar_User()\">Alterar</a>\r\n");
      out.write("            <a href=\"#\" onclick=\"Excluir_User()\">Excluir</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


session.setAttribute("id_User", id);


      out.write("\r\n");
      out.write("\r\n");
      out.write("<a href=\"../Carrinho_de_compras/Carrinho.jsp\"> <span class=\"material-symbols-outlined\" target=\"_self\">shopping_cart</span></a>\r\n");
      out.write("<a href=\"../Carrinho_de_compras/teste.jsp\"><span class=\"material-symbols-outlined\" target=\"_self\">favorite</span></a>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    \r\n");
      out.write("    <div id=\"alterar\" class=\"modal\"><!-- modal alterar -->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("        <div class=\"titulo\">\r\n");
      out.write("          <h1 >Alterar</h1>\r\n");
      out.write("          <h2>Tela de alteração</h2>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"Alterar.jsp\" method=\"post\">\r\n");
      out.write("          <label>Código do usuário:</label>\r\n");
      out.write("          <input type=\"text\" name=\"idcliente\" id=\"idcliente\" disabled=\"disabled\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("          <input type=\"hidden\" name=\"huser\" id=\"huser\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("          <p>Nome:</p>\r\n");
      out.write("          <input type=\"text\" name=\"nome\" id=\"nome\" value=\"");
      out.print( nome);
      out.write("\">\r\n");
      out.write("          <p>E-mail:</p>\r\n");
      out.write("          <input type=\"email\" name=\"email\" id=\"email\" value=\"");
      out.print(email);
      out.write("\" required>\r\n");
      out.write("          <input type=\"hidden\" name=\"email_antigo\" id=\"email_antigo\" value=\"");
      out.print( email);
      out.write("\" >\r\n");
      out.write("          <p>Senha:</p>\r\n");
      out.write("          <input type=\"text\" name=\"senha_alterar\" id=\"senha_alterar\" value=\"");
      out.print( senha);
      out.write("\" required> \r\n");
      out.write("          <button type=\"submit\">Alterar</button>\r\n");
      out.write("        </form>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("   \r\n");
      out.write("    <div id=\"excluir\" class=\"modal\"> <!-- Modal para excluir-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("        <div class=\"titulo\">\r\n");
      out.write("          \r\n");
      out.write("          <h1 style=\"margin-bottom: 20px;\">Tenm certeza que deseja excluir?</h1>\r\n");
      out.write("          <form action=\"Excluir.jsp\" method=\"post\">\r\n");
      out.write("            <label>Código do usuário:</label>\r\n");
      out.write("            <input type=\"text\" name=\"idcliente\" id=\"idcliente\" disabled=\"disabled\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("            <input type=\"hidden\" name=\"huser\" id=\"huser\" value=\"");
      out.print( id );
      out.write("\">\r\n");
      out.write("            <p>Nome:</p>\r\n");
      out.write("            <input type=\"text\" name=\"nome\" id=\"nome\" disabled=\"disabled\" value=\"");
      out.print( nome);
      out.write("\">\r\n");
      out.write("            <p>E-mail:</p>\r\n");
      out.write("            <input type=\"email\" name=\"email\" id=\"email\" disabled=\"disabled\" value=\"");
      out.print( email);
      out.write("\" required>\r\n");
      out.write("            <p>Senha:</p>\r\n");
      out.write("            <input type=\"text\" name=\"senha_alterar\" id=\"senha_alterar\" disabled=\"disabled\" value=\"");
      out.print( senha);
      out.write("\" required> \r\n");
      out.write("            <button type=\"submit\">Excluir</button>\r\n");
      out.write("           </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("     <div id=\"form-carrinho\" class=\"modal\"> <!-- Modal para cadastrar carrinho-->\r\n");
      out.write("      <div class=\"modal-content\">\r\n");
      out.write("        <span class=\"close\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("        <div class=\"titulo\">\r\n");
      out.write("          \r\n");
      out.write("          <h1 style=\"margin-bottom: 20px;\">Produtos</h1>\r\n");
      out.write("          \r\n");
      out.write("     <form id=\"form-carrinho\" action=\"../Carrinho_de_compras/Cadastra_Produto.jsp\" method=\"post\">\r\n");
      out.write("    <label for=\"id_usuario\">Código do Usuário:</label>\r\n");
      out.write("    <input type=\"number\" id=\"id_usuario\" name=\"id_usuario\" required readonly>\r\n");
      out.write("    <input type=\"hidden\" id=\"imagem_url\" name=\"imagem_url\">\r\n");
      out.write("    \r\n");
      out.write("    <label for=\"nome_produto\">Nome do Produto:</label>\r\n");
      out.write("    <input type=\"text\" id=\"nome_produto\" name=\"nome_produto\" required readonly>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"preco\">Preço:</label>\r\n");
      out.write("    <input type=\"text\" id=\"preco\" name=\"preco\" required readonly value=\"Primeiro escolha o tamanho\">\r\n");
      out.write("     <input type=\"hidden\" id=\"preco_padrao\" name=\"preco_padrao\" required >\r\n");
      out.write("\r\n");
      out.write("    <label for=\"quantidade\">Quantidade:</label>\r\n");
      out.write("    <input type=\"number\" id=\"quantidade\" name=\"quantidade\" required>\r\n");
      out.write("\r\n");
      out.write("    <label for=\"tamanho\">Tamanho:</label>\r\n");
      out.write("    <input type=\"hidden\" id=\"tam\" name=\"tam\" >\r\n");
      out.write(" \r\n");
      out.write("<select class=\"select_tamanho\" id=\"tamanho\" onchange=\"atualizarPreco(this.value)\" required>\r\n");
      out.write("  <option value=\"\" disabled selected>Ecolha o tamanho</option>   \r\n");
      out.write("  <option value=\"PP\" data-preco=\"0\" >PP</option>\r\n");
      out.write("  <option value=\"P\" data-preco=\"10.00\">P</option>\r\n");
      out.write("  <option value=\"M\" data-preco=\"11.00\">M</option>\r\n");
      out.write("  <option value=\"G\" data-preco=\"12.00\">G</option>\r\n");
      out.write("  <option value=\"GG\" data-preco=\"13.50\">GG</option>\r\n");
      out.write("</select>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"submit\">Cadastrar Produto</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <div class=\"Meio\">\r\n");
      out.write("      <h1>");
      out.print(nome.toUpperCase());
      out.write(": TEMOS NOVIDADES</h1>\r\n");
      out.write("      <p>Na loja Styloh você encontrará as últimas tendências em moda feminina e várias novidades para você.<br>Monte looks incríveis e estilosos com a nossa variedade de roupas femininas.</p>\r\n");
      out.write("      <button>Nova Coleção</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section>\r\n");
      out.write("      <br>\r\n");
      out.write("      <h1 style=\"margin-top: 40px;\">NOVAS CATEGORIAS</h1>\r\n");
      out.write("      <div class=\"container-card\">\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0004.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0005.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0006.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0007.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0008.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0009.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"cta\">\r\n");
      out.write("      <div class=\"text-cta\">\r\n");
      out.write("        <h6>Monte seu Look aqui</h6>\r\n");
      out.write("        <h4>30% OFF<br>NOVAS ROUPAS</h4>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">Compre agora</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("      <h1>ESTOQUES NOVOS</h1>\r\n");
      out.write("      <div class=\"container-roupas\">\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup1.jpg\">\r\n");
      out.write("          <p>R$45</p>\r\n");
      out.write("<div class=\"preco-container\" onclick=\"Form_carrinho('Cropped preta', 1, '45', 'roupasSite/roup1.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup2.jpg\">\r\n");
      out.write("          <p>R$100</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Calça', 1, '100', 'roupasSite/roup2.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup3.jpg\">\r\n");
      out.write("          <p>R$50</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Cropped verde', 1, '50', 'roupasSite/roup3.jpg', ");
      out.print(id);
      out.write(")\" >Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup4.jpg\">\r\n");
      out.write("          <p>R$70</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Short jeans ', 1, '70', 'roupasSite/roup4.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup5.jpg\">\r\n");
      out.write("          <p>R$63</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Camisa de botão ', 1, '63', 'roupasSite/roup5.jpg', ");
      out.print(id);
      out.write(")\" >Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup7.jpg\">\r\n");
      out.write("          <p>R$85</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Conjunto shorte e regata', 1, '85', 'roupasSite/roup7.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup8.jpg\">\r\n");
      out.write("          <p>R$75</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Conjunto saia e cropped', 1, '75', 'roupasSite/roup8.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup11.jpg\">\r\n");
      out.write("          <p>R$55</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Saia verde', 1, '55', 'roupasSite/roup11.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup9.jpg\">\r\n");
      out.write("          <p>R$49.9</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Conjunto cropped e shorte', 1, '49.90', 'roupasSite/roup9.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup12.jpg\">\r\n");
      out.write("          <p>R$60</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"Form_carrinho('Saia', 1, '60', 'roupasSite/roup12.jpg', ");
      out.print(id);
      out.write(")\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"Sobre\">\r\n");
      out.write("      <h4>Sobre nossa empresa</h4>\r\n");
      out.write("      <p1>A Styloh é uma das principais lojas de roupas femininas do Brasil. É sinônimo de uma moda que traduz as tendências mais atuais de forma estilosa, feminina e com looks perfeitos para você. Fundada em 2023, nossa loja aposta em looks que representam o estilo de vida de mulheres modernas e sofisticadas. Blusas, calças e vestidos perfeitos para todos os momentos, a Styloh é sempre a protagonista quando se fala em moda e estilo.</p1>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"Contato\" id=\"contato\">\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Styloh</h1>\r\n");
      out.write("        <h1>Entre em contato conosco</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Explore</h1>\r\n");
      out.write("        <li><a href=\"#\"> Página inicial</a></li>\r\n");
      out.write("        <li><a href=\"#\">Destaque</a></li>\r\n");
      out.write("        <li><a href=\"#\">Novo</a></li>\r\n");
      out.write("        <li><a href=\"#\">Contato</a></li>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Outros serviços</h1>\r\n");
      out.write("        <li><a href=\"#\">Preços</a></li>\r\n");
      out.write("        <li><a href=\"#\">Frete grátis</a></li>\r\n");
      out.write("        <li><a href=\"#\">Cartões-presente</a></li>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Redes Sociais</h1>\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("          <li><a href=\"#\"><img src=\"img logos/face.png\" alt=\"facebook\" class=\"objetoslogo\"></a></li>\r\n");
      out.write("          <li><a href=\"#\"><img src=\"img logos/wapp.png\" alt=\"whatsapp\" class=\"objetoslogo\"></a></li>\r\n");
      out.write("          <li><a href=\"https://www.instagram.com/looh_lims/\"><img src=\"img logos/insta.png\" alt=\"instagram\" class=\"objetoslogo\"></a></li>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
