/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-07-06 12:30:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Cliente;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import DAO.UserDAO;
import DTO.UserDTO;

public final class raiz_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DTO.UserDTO");
    _jspx_imports_classes.add("DAO.UserDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String nome = request.getParameter("nome");
String email = request.getParameter("email");


      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<style>\r\n");
      out.write(".usuario{\r\n");
      out.write("\r\n");
      out.write("    margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"UTF-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("  <link rel=\"stylesheet\" type=\"text/css\" href=\"style.css\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0\">\r\n");
      out.write("  <title>Lohane Lima</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("  <div class=\"background\">\r\n");
      out.write("    <header>\r\n");
      out.write("      <div class=\"logo\">\r\n");
      out.write("        <h1>Styloh</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"cabeçalho-link\">\r\n");
      out.write("        <a href=\"#\">Inicio</a>\r\n");
      out.write("        <a href=\"#\">Destaque</a>\r\n");
      out.write("        <a href=\"#\">Novo</a>\r\n");
      out.write("        <a href=\"#contato\">Contato</a>\r\n");
      out.write("        <li class=\"dropdown\">\r\n");
      out.write("        <a href=\"#\">Login</a>\r\n");
      out.write("        <div class=\"dropdown-content\">\r\n");
      out.write("          <a href=\"../PG_Principal/index.html\">Sair</a>\r\n");
      out.write("          <a href=\"#\">Alterar</a>\r\n");
      out.write("          <a href=\"#\">Excluir</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        </li>\r\n");
      out.write("        <a href=\"carrinho-cliente.html\"><span class=\"material-symbols-outlined\">shopping_cart</span></a>\r\n");
      out.write("        <a href=\"#\"><span class=\"material-symbols-outlined\">favorite</span></a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"Meio\">\r\n");
      out.write("      <h1>");
      out.print(nome.toUpperCase());
      out.write(": TEMOS NVIDADES</h1>\r\n");
      out.write("     \r\n");
      out.write("      <p>Na loja Styloh você encontrará as últimas tendências em moda feminina e várias novidades para você.<br>Monte looks incríveis e estilosos com a nossa variedade de roupas femininas.</p>\r\n");
      out.write("      <button>Nova Coleção</button>\r\n");
      out.write("    </div>\r\n");
      out.write("    <section>\r\n");
      out.write("        <br>\r\n");
      out.write("      <h1 style=\"margin-top: 40px;\">NOVAS CATEGORIAS</h1>\r\n");
      out.write("      <div class=\"container-card\">\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0004.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0005.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0006.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0007.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0008.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"cards\">\r\n");
      out.write("          <img src=\"roupaCapa/IMG-20230423-WA0009.jpg\">\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"cta\"> \r\n");
      out.write("      <div class=\"text-cta\">\r\n");
      out.write("        <h6>Monte seu Look aqui</h6>\r\n");
      out.write("        <h4>30% OFF<br>NOVAS ROUPAS</h4>\r\n");
      out.write("        <a href=\"#\" class=\"btn\">Compre agora</a>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section>\r\n");
      out.write("      <h1>ESTOQUES NOVOS</h1>\r\n");
      out.write("      <div class=\"container-roupas\">\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup1.jpg\">\r\n");
      out.write("          <p>R$45</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("         \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup2.jpg\">\r\n");
      out.write("          <p>R$100</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup3.jpg\">\r\n");
      out.write("          <p>R$50</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup4.jpg\">\r\n");
      out.write("          <p>R$70</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup5.jpg\">\r\n");
      out.write("          <p>R$63</p>\r\n");
      out.write("          <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup7.jpg\">\r\n");
      out.write("          <p>R$85</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup8.jpg\">\r\n");
      out.write("          <p>R$75</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup11.jpg\">\r\n");
      out.write("          <p>R$55</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup9.jpg\">\r\n");
      out.write("          <p>R$49</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"roupa\">\r\n");
      out.write("          <img src=\"roupasSite/roup12.jpg\">\r\n");
      out.write("          <p>R$55</p>\r\n");
      out.write("            <div class=\"preco-container\" onclick=\"enviarValorImagem('R$45', 'pink1.jpg')\">Comprar<span class=\"material-symbols-outlined\">shopping_cart_checkout</span></div>\r\n");
      out.write("          <ion-icon name=\"cart-outline\"></ion-icon>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"Sobre\">\r\n");
      out.write("      <h4>Sobre nossa empresa</h4>\r\n");
      out.write("      <p1>A Styloh é uma das principais lojas de roupas femininas do Brasil. É sinônimo de uma moda que traduz as tendências mais atuais de forma estilosa, feminina e com looks perfeitos para você. Fundada em 2023, nossa loja aposta em looks que representam o estilo de vida de mulheres modernas e sofisticadas. Blusas, calças e vestidos perfeitos para todos os momentos, a Styloh é sempre a protagonista quando se fala em moda e estilo.</p1>\r\n");
      out.write("    </section>\r\n");
      out.write("    <section class=\"Contato\" id=\"contato\">\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Styloh</h1>\r\n");
      out.write("        <h1>Entre em contato conosco</h1>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Explore</h1>\r\n");
      out.write("        <li><a href=\"#\"> Página inicial</a></li>\r\n");
      out.write("        <li><a href=\"#\">Destaque</a></li>\r\n");
      out.write("        <li><a href=\"#\">Novo</a></li>\r\n");
      out.write("        <li><a href=\"#\">Contato</a></li>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Outros serviços</h1>\r\n");
      out.write("        <li><a href=\"#\">Preços</a></li>\r\n");
      out.write("        <li><a href=\"#\">Frete grátis</a></li>\r\n");
      out.write("        <li><a href=\"#\">Cartões-presente</a></li>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"meio-contato\">\r\n");
      out.write("        <h1>Redes Sociais</h1>\r\n");
      out.write("        <div class=\"logo-container\">\r\n");
      out.write("          <li><a href=\"#\"><img src=\"img logos/face.png\" alt=\"facebook\" class=\"objetoslogo\"></a></li>\r\n");
      out.write("          <li><a href=\"#\"><img src=\"img logos/wapp.png\" alt=\"whatsapp\" class=\"objetoslogo\"></a></li>\r\n");
      out.write("          <li><a href=\"#\"><img src=\"img logos/insta.png\" alt=\"instagram\" class=\"objetoslogo\"></a></li> \r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </section>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
