/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-09-24 16:04:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import DTO.UserDTO;
import DAO.UserDAO;
import DAO.ProdutoDAO;
import DTO.ProdutoDTO;
import java.util.ArrayList;

public final class Lista_005fprodutos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DTO.UserDTO");
    _jspx_imports_classes.add("DAO.ProdutoDAO");
    _jspx_imports_classes.add("DAO.UserDAO");
    _jspx_imports_classes.add("DTO.ProdutoDTO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0\" />\r\n");
      out.write("    <title>Lista de compras ADM</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("    @charset \"ISO-8859-1\";\r\n");
      out.write("    /* Reset de Estilos */\r\n");
      out.write("    * {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("    }\r\n");
      out.write("    /* Estilos Globais */\r\n");
      out.write("    body {\r\n");
      out.write("    background: #fde3d8;\r\n");
      out.write("    font-family: 'Lato', sans-serif;\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("    header {\r\n");
      out.write("    background: #111;\r\n");
      out.write("    color: white;\r\n");
      out.write("    font-size: 24px;\r\n");
      out.write("    padding: 20px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    main {\r\n");
      out.write("    background: #fde3d8;\r\n");
      out.write("    padding: 0 30px 0;\r\n");
      out.write("    }\r\n");
      out.write("    .page-title {\r\n");
      out.write("    font-size: 40px;\r\n");
      out.write("    padding: 50px 0;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("    .home{\r\n");
      out.write("    padding:10px;\r\n");
      out.write("    background-color:#fdfdfd;\r\n");
      out.write("    position:absolute;\r\n");
      out.write("    border-radius:90px;\r\n");
      out.write("    margin-top:50px;\r\n");
      out.write("    transition:.50s;\r\n");
      out.write("    cursor:pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .home:hover{\r\n");
      out.write("    background-color:#6b6a6a;\r\n");
      out.write("    color:white;\r\n");
      out.write("    }\r\n");
      out.write("    .content {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    }\r\n");
      out.write("    .content section {\r\n");
      out.write("    flex: 1;\r\n");
      out.write("    }\r\n");
      out.write("    .content aside {\r\n");
      out.write("    min-width: 250px;\r\n");
      out.write("    }\r\n");
      out.write("    /* Botões e Elementos Interativos */\r\n");
      out.write("    button {\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    font-family: 'Lato', sans-serif;\r\n");
      out.write("    }\r\n");
      out.write("    /* Tabela de Produtos */\r\n");
      out.write("    table {\r\n");
      out.write("    background: #fff;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    border-collapse: collapse;\r\n");
      out.write("    }\r\n");
      out.write("    th, td {\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("    }\r\n");
      out.write("    th {\r\n");
      out.write("    padding:5px;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    color: #3e3e3e;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    background-color: lightgray;\r\n");
      out.write("    }\r\n");
      out.write("    tr {\r\n");
      out.write("    border-bottom: 3px solid #eee;\r\n");
      out.write("    }\r\n");
      out.write("    tr:last-child {\r\n");
      out.write("    border: none;\r\n");
      out.write("    }\r\n");
      out.write("    /* Imagens de Produtos */\r\n");
      out.write("    img {\r\n");
      out.write("    margin-top:4px;\r\n");
      out.write("    max-width: 100px;\r\n");
      out.write("    max-height: 100px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    }\r\n");
      out.write("    /* Quantidade de Produtos */\r\n");
      out.write("    .qty {\r\n");
      out.write("    background: #c7c7c7;\r\n");
      out.write("    display: inline-flex;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    justify-content: space-around;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    height: 25px;\r\n");
      out.write("    }\r\n");
      out.write("    .qty span {\r\n");
      out.write("    margin: 0 5px;\r\n");
      out.write("    }\r\n");
      out.write("    .qty button {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: none;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    .qty button:hover {\r\n");
      out.write("    background: #ddd;\r\n");
      out.write("    }\r\n");
      out.write("    /* Botão de Remoção */\r\n");
      out.write("    .remove  {\r\n");
      out.write("    background: #c7c7c7;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding:5px;\r\n");
      out.write("    border-radius: 100%;\r\n");
      out.write("    font-size: 20px;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .remove:hover {\r\n");
      out.write("    background: #ddd;\r\n");
      out.write("    }\r\n");
      out.write("    /* Resumo da Compra */\r\n");
      out.write("    .box {\r\n");
      out.write("    margin-left:20px;\r\n");
      out.write("    margin-bottom: 15px;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    background: #eee;\r\n");
      out.write("    color: #222;\r\n");
      out.write("    }\r\n");
      out.write("    .box header {\r\n");
      out.write("    padding: 15px 20px;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    border-bottom: 1px solid #ccc;\r\n");
      out.write("    }\r\n");
      out.write("    .box .info {\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("    .box .info > div {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    margin-bottom: 10px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    }\r\n");
      out.write("    .box .info > div:last-child {\r\n");
      out.write("    margin: 0;\r\n");
      out.write("    }\r\n");
      out.write("    .box .info button {\r\n");
      out.write("    color:rgb(233 188 129);\r\n");
      out.write("    background: transparent;\r\n");
      out.write("    border: none;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    }\r\n");
      out.write("    .box footer {\r\n");
      out.write("    padding: 15px 20px;\r\n");
      out.write("    background: #ddd;\r\n");
      out.write("    font-size: 18px;\r\n");
      out.write("    display: flex;\r\n");
      out.write("    justify-content: space-between;\r\n");
      out.write("    }\r\n");
      out.write("    aside > button {\r\n");
      out.write("    margin-left:20px;\r\n");
      out.write("    border: none;\r\n");
      out.write("    padding: 15px 0;\r\n");
      out.write("    color: white;\r\n");
      out.write("    background: rgb(233, 188, 129);\r\n");
      out.write("    display: block;\r\n");
      out.write("    width: 93%;\r\n");
      out.write("    text-transform: uppercase;\r\n");
      out.write("    letter-spacing: 1px;\r\n");
      out.write("    font-size: 16px;\r\n");
      out.write("    border-radius: 9px\r\n");
      out.write("    }\r\n");
      out.write("    aside > button:hover {\r\n");
      out.write("    background: rgb(233 188 129 / 72%);\r\n");
      out.write("    }\r\n");
      out.write("    .tiulo_aside{\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    color: white;	\r\n");
      out.write("    }\r\n");
      out.write("    .titulo_div_aside{\r\n");
      out.write("    background: black;	\r\n");
      out.write("    padding: 10px 0 ;\r\n");
      out.write("    }\r\n");
      out.write("    a{\r\n");
      out.write("    color: #111;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    }\r\n");
      out.write("    .modal {\r\n");
      out.write("    display: none;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("    z-index: 1;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    top: 0;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    background-color: rgba(0, 0, 0, 0.8);\r\n");
      out.write("    }\r\n");
      out.write("    .modal-content {\r\n");
      out.write("    background-color:#fff;\r\n");
      out.write("    margin: 15% auto;\r\n");
      out.write("    padding: 20px;\r\n");
      out.write("    border: 1px solid #888;\r\n");
      out.write("    width: 20%;\r\n");
      out.write("    text-align: center;\r\n");
      out.write("    border-radius:10px; \r\n");
      out.write("    }\r\n");
      out.write("    .close {\r\n");
      out.write("    margin-top:-20px;\r\n");
      out.write("    margin-right:-15px;\r\n");
      out.write("    color: #555;\r\n");
      out.write("    float: right;\r\n");
      out.write("    font-size: 30px;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("    .close:hover {\r\n");
      out.write("    color: black;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .butt-deletar{\r\n");
      out.write("    padding: 5px 7px;\r\n");
      out.write("    color: #fff;\r\n");
      out.write("    background-color: #f00;\r\n");
      out.write("    border-radius: 6px;\r\n");
      out.write("    }\r\n");
      out.write("    .butt-deletar:hover{\r\n");
      out.write("    background-color: #000;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("    .select_tamanho{\r\n");
      out.write("    background: #c7c7c7;\r\n");
      out.write("    border:none;\r\n");
      out.write("    padding: 5px 10px;\r\n");
      out.write("    border-radius: 20px;\r\n");
      out.write("    overflow: hidden;\r\n");
      out.write("    height: 25px; \r\n");
      out.write("    } \r\n");
      out.write("  </style>\r\n");
      out.write("  <body>\r\n");
      out.write("    ");

      ProdutoDAO Listar_Produto = new ProdutoDAO();
      ArrayList<ProdutoDTO> users = Listar_Produto.ListarProdutos();
      int id_Produto= 0;
      
      int id_user = 0;
      
      double preco = 0;
      int quantidade = 0;
      UserDAO listar = new UserDAO();
      ArrayList<UserDTO> lista = listar.ArrayListarUser();
      
      
      
      
      out.write("\r\n");
      out.write("    <header>\r\n");
      out.write("      <span>Carrinho de vendas do <b>ADM</b></span>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main>\r\n");
      out.write("      \r\n");
      out.write("      <div class=\"page-title\"> Seu Carrinho</div>\r\n");
      out.write("      <div class=\"content\">\r\n");
      out.write("        <section>\r\n");
      out.write("          <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <th>efjoj</th>\r\n");
      out.write("              <th>Comprador</th>\r\n");
      out.write("              <th>Código produto</th>\r\n");
      out.write("              <th>Img</th>\r\n");
      out.write("              <th>Nome</th>\r\n");
      out.write("              <th>Preço</th>\r\n");
      out.write("              <th>Quantidade</th>\r\n");
      out.write("              <th>Tamanho</th>\r\n");
      out.write("              <th>Sub-total</th>\r\n");
      out.write("              <th>Deletar</th>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tbody>\r\n");
      out.write("              ");

                int id_de_Procura = 0;
              double total = 0;

              for (UserDTO cliente : lista) {
                  id_de_Procura = cliente.getId_user();
                  boolean encontrou = false;

                  for (ProdutoDTO user : users) {
                      if (user.getUsuario().getId_user() == id_de_Procura) {
                          encontrou = true;

                          double sub_total = (user.getQuantidade() * user.getPreco()); 
                          total += sub_total;
                
      out.write("   \r\n");
      out.write("              <tr>\r\n");
      out.write("                <td>");
      out.print( cliente.getId_user() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( cliente.getNome() );
      out.write("</td>\r\n");
      out.write("                <td>");
      out.print( user.getId_produto());
      out.write("</td>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"product\">\r\n");
      out.write("                    <img src=\"");
      out.print(user.getImagem_url());
      out.write("\" alt=\"imagem do produto\"> \r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"info\">\r\n");
      out.write("                    <div class=\"category\">Categoria</div>\r\n");
      out.write("                    <div class=\"name\">");
      out.print( user.getNome_produto() );
      out.write("</div>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td> R$ <span id=\"preco_");
      out.print( user.getId_produto() );
      out.write('"');
      out.write('>');
      out.print( user.getPreco());
      out.write("</span></td>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <div class=\"qty\">\r\n");
      out.write("                    <button onclick=\"diminuirQuantidade(");
      out.print( user.getId_produto() );
      out.write(',');
      out.write(' ');
      out.print( user.getPreco());
      out.write(',');
      out.write(' ');
      out.print(cliente.getId_user());
      out.write(")\">\r\n");
      out.write("                    <span class=\"material-symbols-outlined\">remove</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                    <span class=\"qry_meio\" id=\"quantidade_");
      out.print( user.getId_produto() );
      out.write('"');
      out.write('>');
      out.print( user.getQuantidade());
      out.write("</span>\r\n");
      out.write("                    <button onclick=\"aumentarQuantidade(");
      out.print( user.getId_produto() );
      out.write(',');
      out.write(' ');
      out.print( user.getPreco() );
      out.write(',');
      out.print(cliente.getId_user());
      out.write(")\">\r\n");
      out.write("                    <span class=\"material-symbols-outlined tam\">add</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>\r\n");
      out.write("                  <select class=\"select_tamanho\" id=\"tamanho_");
      out.print( user.getId_produto() );
      out.write("\" onchange=\"changeTamanho(this, '");
      out.print( user.getId_produto() );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(id_de_Procura);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print( user.getSub_total());
      out.write("')\">\r\n");
      out.write("                    <option value=\"\" disabled selected>");
      out.print( user.getTamanho());
      out.write("</option>\r\n");
      out.write("                    <option value=\"PP\" data-preco=\"0\">PP</option>\r\n");
      out.write("                    <option value=\"P\" data-preco=\"10.00\">P</option>\r\n");
      out.write("                    <option value=\"M\" data-preco=\"11.00\">M</option>\r\n");
      out.write("                    <option value=\"G\" data-preco=\"12.00\">G</option>\r\n");
      out.write("                    <option value=\"GG\" data-preco=\"13.50\">GG</option>\r\n");
      out.write("                  </select>\r\n");
      out.write("                </td>\r\n");
      out.write("                <td>R$ <span id=\"subtotal_");
      out.print( user.getId_produto() );
      out.write('"');
      out.write('>');
      out.print( user.getQuantidade() * user.getPreco() );
      out.write("</span></td>\r\n");
      out.write("                <td><span class=\"material-symbols-outlined remove \" onclick=\"openModalDeletar('");
      out.print(id_de_Procura );
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(user.getId_produto() );
      out.write("')\">close</span></td>\r\n");
      out.write("              </tr>\r\n");
      out.write("              ");

                }
                }
                
                
                  }
                
                  
      out.write("\r\n");
      out.write("          </table>\r\n");
      out.write("          </tbody>\r\n");
      out.write("          </table>\r\n");
      out.write("          <!-- modal deletar -->\r\n");
      out.write("          <div id=\"myModal\" class=\"modal\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("              <span class=\"close\" id=\"closeModalBtn\" onclick=\"closeModal()\">&times;</span>\r\n");
      out.write("              <br>\r\n");
      out.write("              <p>Tem certeza de que deseja excluir este produto?</p>\r\n");
      out.write("              <br>\r\n");
      out.write("<a class=\"butt-deletar\"  onclick=\"enviar_for_deleta()\"><b>Sim, Excluir<b></a>            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </section>\r\n");
      out.write("        <aside>\r\n");
      out.write("          <div class=\"box\">\r\n");
      out.write("            <div class=\"titulo_div_aside\">\r\n");
      out.write("              <h1 class=\"tiulo_aside\">\r\n");
      out.write("              Total de vendas</header>\r\n");
      out.write("            </div>\r\n");
      out.write("           \r\n");
      out.write("            <footer>\r\n");
      out.write("              <span>Total</span>\r\n");
      out.write("              <span>R$ ");
      out.print(total);
      out.write("</span>\r\n");
      out.write("            </footer>\r\n");
      out.write("          </div>\r\n");
      out.write("          <button>Mandar para entrega</button>\r\n");
      out.write("        </aside>\r\n");
      out.write("      </div>\r\n");
      out.write("    </main>\r\n");
      out.write("    <form action=\"Altera_quantidade.jsp\" method=\"post\" id=\"quantidadeForm\">\r\n");
      out.write("      <input type=\"hidden\" name=\"id_User_quantidade\" id=\"id_User_quantidade\" >\r\n");
      out.write("      <input type=\"hidden\" name=\"id_produto\" id=\"id_produto\">\r\n");
      out.write("      <input type=\"hidden\" name=\"quantidade\" id=\"quantidade\">\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"Altera_tamanho.jsp\" method=\"post\" id=\"tamnhoForm\">\r\n");
      out.write("      <input type=\"hidden\" name=\"id_User_tamanho\" id=\"id_User_tamanho\">\r\n");
      out.write("      <input type=\"hidden\" name=\"preco_por_tamanho\" id=\"preco_por_tamanho\">\r\n");
      out.write("      <input type=\"hidden\" name=\"id_produtoo\" id=\"id_produtoo\">\r\n");
      out.write("      <input type=\"hidden\" name=\"tamanho\" id=\"tamanho\">\r\n");
      out.write("    </form>\r\n");
      out.write("    \r\n");
      out.write("    <form action=\"Deletar_Produto.jsp\" method=\"post\" id=\"deletar\">\r\n");
      out.write("      <input type=\"hidden\" name=\"id_produto_deletar\" id=\"id_produto_deletar\">\r\n");
      out.write("      <input type=\"hidden\" name=\"id_user_deletar\" id=\"id_user_deletar\">\r\n");
      out.write("    </form>\r\n");
      out.write("    <script>\r\n");
      out.write("    function enviar_for_deleta() {\r\n");
      out.write("     	document.getElementById(\"deletar\").submit();\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("      	\r\n");
      out.write("    function openModalDeletar(id_user , idProduto) {\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        modal.style.display = \"block\";\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById(\"id_produto_deletar\").value = idProduto;\r\n");
      out.write("  	  document.getElementById(\"id_user_deletar\").value = id_user;\r\n");
      out.write("  	  \r\n");
      out.write(" \r\n");
      out.write("      }\r\n");
      out.write("    \r\n");
      out.write("    function return_index(){\r\n");
      out.write("    	document.getElementById(\"return_index\").submit();\r\n");
      out.write("    }\r\n");
      out.write("      // Função para fechar o modal\r\n");
      out.write("      function closeModal() {\r\n");
      out.write("        var modal = document.getElementById(\"myModal\");\r\n");
      out.write("        modal.style.display = \"none\";\r\n");
      out.write("      }\r\n");
      out.write("       \r\n");
      out.write("      	\r\n");
      out.write("      	\r\n");
      out.write("      	\r\n");
      out.write("      	\r\n");
      out.write("      // Função para aumentar a quantidade de um produto\r\n");
      out.write("      	  function subtotal(subtotalSpan, subtotalValue,quantidade, idProduto, id) {\r\n");
      out.write("      	  subtotalSpan.textContent = subtotalValue;\r\n");
      out.write("      	  \r\n");
      out.write("      	  var quantidadeSpan = document.getElementById(\"quantidade_\" + idProduto);\r\n");
      out.write("      	  document.getElementById(\"id_produto\").value = idProduto;\r\n");
      out.write("      	  document.getElementById(\"quantidade\").value = quantidade;\r\n");
      out.write("      	  document.getElementById(\"id_User_quantidade\").value = id;\r\n");
      out.write("      	  \r\n");
      out.write("      	  document.getElementById(\"quantidadeForm\").submit();\r\n");
      out.write("      	  \r\n");
      out.write("      	}\r\n");
      out.write("\r\n");
      out.write("      	function aumentarQuantidade(idProduto, preco, id) {\r\n");
      out.write("      	  var quantidadeSpan = document.getElementById(\"quantidade_\" + idProduto);\r\n");
      out.write("      	  var quantidade = parseInt(quantidadeSpan.textContent);\r\n");
      out.write("      	  quantidade++;\r\n");
      out.write("      	  quantidadeSpan.textContent = quantidade;\r\n");
      out.write("\r\n");
      out.write("      	  var subtotalSpan = document.getElementById(\"subtotal_\" + idProduto);\r\n");
      out.write("      	  var subtotalValue = (quantidade * preco).toFixed(1);\r\n");
      out.write("      	  \r\n");
      out.write("      	  subtotal(subtotalSpan, subtotalValue, quantidade, idProduto, id);\r\n");
      out.write("      	} \r\n");
      out.write("\r\n");
      out.write("      	// Função para diminuir a quantidade de um produto\r\n");
      out.write("      	function diminuirQuantidade(idProduto, preco, id) {\r\n");
      out.write("      	  var quantidadeSpan = document.getElementById(\"quantidade_\" + idProduto);\r\n");
      out.write("      	  var quantidade = parseInt(quantidadeSpan.textContent);\r\n");
      out.write("      	  if (quantidade > 0) {\r\n");
      out.write("      	    quantidade--;\r\n");
      out.write("      	    quantidadeSpan.textContent = quantidade;\r\n");
      out.write("\r\n");
      out.write("      	    var subtotalSpan = document.getElementById(\"subtotal_\" + idProduto);\r\n");
      out.write("      	    var subtotalValue = (quantidade * preco).toFixed(1);\r\n");
      out.write("\r\n");
      out.write("      	    subtotal(subtotalSpan, subtotalValue, quantidade, idProduto, id);\r\n");
      out.write("      	  }\r\n");
      out.write("      	}\r\n");
      out.write("      	\r\n");
      out.write("      	\r\n");
      out.write("      	\r\n");
      out.write("	      	 function changeTamanho(selectElement, idProduto, id, valor_padrao) {\r\n");
      out.write("	             // Obtenha a opção selecionada no <select>\r\n");
      out.write("	             var selectedOption = selectElement.options[selectElement.selectedIndex];\r\n");
      out.write("	            \r\n");
      out.write("	             // Obtenha o valor da opção selecionada\r\n");
      out.write("	             var tamanhoSelecionado = selectedOption.value;\r\n");
      out.write("	            \r\n");
      out.write("	             // Defina o valor da opção selecionada no elemento 'tamanho'\r\n");
      out.write("	             document.getElementById(\"tamanho\").value = tamanhoSelecionado;\r\n");
      out.write("	             document.getElementById(\"id_produtoo\").value = idProduto;\r\n");
      out.write("	             document.getElementById(\"id_User_tamanho\").value = id;\r\n");
      out.write("	             \r\n");
      out.write("	             var preco = parseFloat(selectedOption.getAttribute(\"data-preco\"));\r\n");
      out.write("	            \r\n");
      out.write("	           \r\n");
      out.write("	            preco_padrao = parseFloat(valor_padrao);\r\n");
      out.write("	             document.getElementById(\"preco_por_tamanho\").value = preco_padrao + preco;\r\n");
      out.write("	             \r\n");
      out.write("	             document.getElementById(\"tamnhoForm\").submit();\r\n");
      out.write("	         \r\n");
      out.write("	            }\r\n");
      out.write("	            \r\n");
      out.write("    </script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
